# Generated by Django 4.2.7 on 2026-03-30 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_us_role_idx_accounts_us_role_1fa9a5_idx_and_more'),
        ('core', '0003_resultrelease'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance',
        ),
        migrations.RemoveConstraint(
            model_name='result',
            name='unique_result',
        ),
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_section',
        ),
        migrations.RemoveConstraint(
            model_name='timetable',
            name='unique_timetable_slot',
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Leave blank for all branches', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='year',
            field=models.ForeignKey(blank=True, help_text='Leave blank for all years', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.year'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='year',
            field=models.IntegerField(db_index=True, help_text='Academic year the paper was set, e.g. 2023'),
        ),
        migrations.AlterField(
            model_name='result',
            name='grade',
            field=models.CharField(blank=True, choices=[('O', 'Outstanding (O)'), ('A+', 'Excellent (A+)'), ('A', 'Very Good (A)'), ('B+', 'Good (B+)'), ('B', 'Above Average (B)'), ('C', 'Average (C)'), ('F', 'Fail (F)'), ('Ab', 'Absent (Ab)')], max_length=3),
        ),
        migrations.AlterField(
            model_name='result',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resultrelease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='year',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'timetable_entry', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('student', 'exam', 'subject')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('name', 'branch', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('section', 'day', 'period')},
        ),
        migrations.AddIndex(
            model_name='academiccalendar',
            index=models.Index(fields=['date', 'event_type'], name='core_academ_date_d38e2e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='core_attend_student_931c39_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['timetable_entry', 'date'], name='core_attend_timetab_a0167c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='core_attend_date_801bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['branch', 'year', 'semester'], name='core_exam_branch__143382_idx'),
        ),
        migrations.AddIndex(
            model_name='questionpaper',
            index=models.Index(fields=['subject', 'year', 'semester'], name='core_questi_subject_fc1229_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'exam'], name='core_result_student_07e1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['exam', 'subject'], name='core_result_exam_id_b5c822_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['branch', 'year', 'semester'], name='core_subjec_branch__12a930_idx'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['section', 'day'], name='core_timeta_section_10bce0_idx'),
        ),
    ]
