# Generated by Django 4.2.7 on 2026-05-11 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_result_final_total_score_alter_result_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notif_type', models.CharField(choices=[('result', 'Result Released'), ('attendance', 'Attendance Alert'), ('announcement', 'Announcement'), ('exam', 'Exam Notice'), ('holiday', 'Holiday Notice'), ('system', 'System')], db_index=True, default='announcement', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('link', models.CharField(blank=True, help_text='Optional URL to navigate to when clicked', max_length=300)),
                ('target_all', models.BooleanField(default=True, help_text='Send to every user')),
                ('target_role', models.CharField(blank=True, help_text="'student', 'faculty', 'admin', etc. — leave blank for all", max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification hidden after this date/time', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('target_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.branch')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='event_type',
            field=models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Examination'), ('event', 'University Event'), ('deadline', 'Deadline'), ('other', 'Other')], db_index=True, default='other', max_length=15),
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='core.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Read',
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
