# Generated by Django 4.2.7 on 2026-06-02 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notification_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='core.section'),
        ),
    ]
