# Generated by Django 4.2.7 on 2026-08-07 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_user_deleted_at_user_deleted_by_name_user_is_deleted'),
        ('core', '0008_notification_deleted_at_notification_deleted_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='room_number',
            field=models.CharField(blank=True, default='Room 101', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FacultyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'On Leave')], default='P', max_length=1)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_attendance_records', to='accounts.faculty')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'faculty'],
                'indexes': [models.Index(fields=['faculty', 'date'], name='core_facult_faculty_88fa59_idx'), models.Index(fields=['date'], name='core_facult_date_4833d3_idx')],
                'unique_together': {('faculty', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClassTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('pending', 'Pending'), ('completed', 'Completed')], default='accepted', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_given', to='accounts.faculty')),
                ('substitute_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_received', to='accounts.faculty')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timetable')),
            ],
            options={
                'ordering': ['-date', 'timetable_entry__period'],
                'indexes': [models.Index(fields=['substitute_faculty', 'date'], name='core_classt_substit_512661_idx'), models.Index(fields=['original_faculty', 'date'], name='core_classt_origina_5a4f6b_idx')],
                'unique_together': {('timetable_entry', 'date')},
            },
        ),
    ]
