# Generated by Django 4.2.7 on 2026-08-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_branch_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
