# Generated by Django 6.1 on 2026-08-13 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_branch_course_delete_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtransfer',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Set True once 15-min advance SMS/email reminder is sent'),
        ),
    ]
