# Generated by Django 6.1 on 2026-08-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_studentfee_amount_paid_and_more'),
        ('core', '0012_classtransfer_reminder_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('period', models.IntegerField(default=1)),
                ('topic_covered', models.CharField(help_text='Core topic or chapter covered in class', max_length=255)),
                ('discussion_summary', models.TextField(blank=True, help_text='Key takeaways, concepts, or theorems discussed')),
                ('homework_assignment', models.TextField(blank=True, help_text='Homework, practice problems, or reading material assigned')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_logs', to='accounts.faculty')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_logs', to='core.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_logs', to='core.subject')),
                ('timetable_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='core.timetable')),
            ],
            options={
                'verbose_name': 'Class Diary',
                'verbose_name_plural': 'Class Diaries',
                'ordering': ['-date', 'period'],
                'unique_together': {('timetable_entry', 'date')},
            },
        ),
    ]
