# Generated by Django 6.1 on 2026-08-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_classdiary'),
    ]

    operations = [
        migrations.AddField(
            model_name='classdiary',
            name='unit_number',
            field=models.IntegerField(choices=[(1, 'Unit 1'), (2, 'Unit 2'), (3, 'Unit 3'), (4, 'Unit 4'), (5, 'Unit 5'), (6, 'Other / Revision / Lab')], db_index=True, default=1, help_text='Syllabus unit number (1 to 5, or Other/Revision)'),
        ),
    ]
