# Generated by Django 4.2.7 on 2026-08-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_classdiary_unit_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyattendance',
            name='status',
            field=models.CharField(choices=[('P', 'Present'), ('A', 'Absent'), ('L', 'On Leave'), ('HD', 'Half Day (0.5D)')], default='P', max_length=5),
        ),
    ]
