# Generated by Django 4.2.7 on 2026-08-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_facultyattendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyattendance',
            name='absent_locked_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp until which this Absent status cannot be modified (3-hour lockout).', null=True),
        ),
    ]
