# Generated by Django 4.2.7 on 2026-08-29 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_faculty_monthly_leave_limit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_facultyattendance_absent_locked_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTopicPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField(choices=[(1, 'Unit 1'), (2, 'Unit 2'), (3, 'Unit 3'), (4, 'Unit 4'), (5, 'Unit 5'), (6, 'Other / Revision / Lab')], db_index=True, default=1)),
                ('unit_title', models.CharField(blank=True, help_text='e.g. Unit 1: Introduction to Data Structures', max_length=150, null=True)),
                ('topic_name', models.CharField(help_text='Specific topic / chapter name to be covered', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed concepts, subtopics, or learning outcomes', null=True)),
                ('target_date', models.DateField(db_index=True, help_text='Target completion date for this topic')),
                ('target_milestone', models.CharField(choices=[('mid1', 'Before Mid-1 Exam (Units 1 – 2.5)'), ('mid2', 'Before Mid-2 Exam (Units 2.5 – 5.0)'), ('final', 'Before Semester Final Exam (Revision / Full Syllabus)')], db_index=True, default='mid1', max_length=15)),
                ('order', models.PositiveIntegerField(default=1, help_text='Sequence order within unit')),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_date', models.DateField(blank=True, db_index=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_diary_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_plan_links', to='core.classdiary')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_topics', to='accounts.faculty')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_plans', to='core.subject')),
            ],
            options={
                'ordering': ['unit_number', 'order', 'target_date'],
                'indexes': [models.Index(fields=['subject', 'unit_number'], name='core_subjec_subject_7f5240_idx'), models.Index(fields=['subject', 'is_completed'], name='core_subjec_subject_75b5bb_idx'), models.Index(fields=['target_date', 'is_completed'], name='core_subjec_target__fbf75d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(choices=[(1, 'Sem 1'), (2, 'Sem 2'), (3, 'Sem 3'), (4, 'Sem 4'), (5, 'Sem 5'), (6, 'Sem 6'), (7, 'Sem 7'), (8, 'Sem 8')], db_index=True)),
                ('exam_type', models.CharField(choices=[('mid1', 'Mid Term 1 (Mid-1)'), ('mid2', 'Mid Term 2 (Mid-2)'), ('final', 'Semester Final Examination'), ('supply', 'Supplementary Examination')], db_index=True, default='mid1', max_length=15)),
                ('title', models.CharField(help_text='e.g. B.Tech CSE II Year Sem-1 Mid-1 Examinations', max_length=150)),
                ('start_date', models.DateField(db_index=True, help_text='Exam commencement date')),
                ('end_date', models.DateField(blank=True, help_text='Exam conclusion date', null=True)),
                ('target_units', models.DecimalField(decimal_places=1, default=2.5, help_text='Required syllabus units to be completed before this exam (e.g. 2.5 for Mid-1, 5.0 for Mid-2)', max_digits=4)),
                ('target_completion_date', models.DateField(db_index=True, help_text='Deadline date for faculty to complete the required syllabus units')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Branch/Department (null for all branches)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_schedules', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.year')),
            ],
            options={
                'ordering': ['start_date', 'year', 'semester'],
                'indexes': [models.Index(fields=['branch', 'year', 'semester', 'exam_type'], name='core_examsc_branch__522336_idx'), models.Index(fields=['target_completion_date'], name='core_examsc_target__316ff5_idx')],
            },
        ),
    ]
