# Generated by Django 4.2.7 on 2026-08-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_subjecttopicplan_examschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionpaper',
            options={'ordering': ['-academic_year', '-semester', 'regulation']},
        ),
        migrations.RemoveIndex(
            model_name='questionpaper',
            name='core_questi_subject_fc1229_idx',
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='academic_year',
            field=models.CharField(db_index=True, default='25 - 26', help_text='Academic year e.g. 25 - 26, 24 - 25', max_length=20),
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='regulation',
            field=models.CharField(db_index=True, default='R23', help_text='e.g. R23, R20, R19, R16', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, help_text='Calendar year the paper was set, e.g. 2025', null=True),
        ),
        migrations.AddIndex(
            model_name='questionpaper',
            index=models.Index(fields=['subject', 'regulation', 'academic_year', 'semester'], name='core_questi_subject_9213bb_idx'),
        ),
    ]
