# Generated by Django 4.2.7 on 2026-08-31 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_alter_questionpaper_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtransfer',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_class_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='assigned_by_role',
            field=models.CharField(choices=[('hod', 'HOD Proxy'), ('admin', 'Admin Proxy'), ('faculty', 'Faculty Substituted Session')], db_index=True, default='faculty', max_length=20),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='transfer_type',
            field=models.CharField(choices=[('proxy', 'Official Proxy (HOD / Admin)'), ('substitution', 'Substituted Session (Faculty)')], db_index=True, default='substitution', max_length=25),
        ),
        migrations.AddIndex(
            model_name='classtransfer',
            index=models.Index(fields=['assigned_by_role', 'date'], name='core_classt_assigne_33a6f6_idx'),
        ),
    ]
