# Generated by Django 6.1 on 2026-09-14 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_student_academic_status_student_detention_reason_and_more'),
        ('core', '0019_classtransfer_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='co_faculty_display',
            field=models.CharField(blank=True, help_text='e.g. Dr. S. Krishna Prasad / Dr. I.L.J. Baktha Singh for multi-faculty labs', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='SectionTimetableMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2026-27', max_length=50)),
                ('room_number', models.CharField(default='C-402', max_length=50)),
                ('with_effect_from', models.DateField(blank=True, null=True)),
                ('class_teacher_name', models.CharField(blank=True, max_length=150, null=True)),
                ('program_name', models.CharField(blank=True, help_text='e.g. Computer Science and Engineering (Internet of Things) – CSO', max_length=255, null=True)),
                ('timetable_incharge', models.CharField(blank=True, default='Timetable I/C', max_length=150)),
                ('hod_name', models.CharField(blank=True, default='HOD', max_length=150)),
                ('dean_academics_name', models.CharField(blank=True, default='Dean, Academics', max_length=150)),
                ('principal_name', models.CharField(blank=True, default='Principal', max_length=150)),
                ('legend_data', models.JSONField(blank=True, default=list, help_text='List of subjects with code, full name, and faculty names')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher_timetables', to='accounts.faculty')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_metadata', to='core.section')),
            ],
            options={
                'verbose_name': 'Section Timetable Metadata',
                'verbose_name_plural': 'Section Timetable Metadata',
            },
        ),
    ]
