# Generated by Django 4.2.7 on 2026-09-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_timetable_co_faculty_display_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtransfer',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='classtransfer',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classtransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Acceptance'), ('accepted', 'Accepted'), ('rejected', 'Declined'), ('completed', 'Completed')], db_index=True, default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('result', 'Result Released'), ('attendance', 'Attendance Alert'), ('announcement', 'Announcement'), ('exam', 'Exam Notice'), ('holiday', 'Holiday Notice'), ('system', 'System'), ('proxy', 'Proxy Request')], db_index=True, default='announcement', max_length=20),
        ),
        migrations.AddIndex(
            model_name='classtransfer',
            index=models.Index(fields=['status', 'date'], name='core_classt_status_c13f3b_idx'),
        ),
    ]
