# Generated by Django 6.1 on 2026-09-15 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_student_academic_status_student_detention_reason_and_more'),
        ('core', '0021_classtransfer_rejection_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Faculty Performance Evaluation - Even Semester', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Instructions and evaluation guidelines for students', null=True)),
                ('feedback_type', models.CharField(choices=[('faculty', 'Faculty Teaching Evaluation'), ('course', 'Course & Curriculum Feedback'), ('institutional', 'Institutional Facilities & Infrastructure'), ('general', 'General Student Feedback')], db_index=True, default='faculty', max_length=30)),
                ('semester', models.IntegerField(blank=True, choices=[(1, 'Sem 1'), (2, 'Sem 2'), (3, 'Sem 3'), (4, 'Sem 4'), (5, 'Sem 5'), (6, 'Sem 6'), (7, 'Sem 7'), (8, 'Sem 8')], db_index=True, help_text='Semester (Leave blank for all semesters)', null=True)),
                ('uploaded_document', models.FileField(blank=True, help_text='Official feedback form document (Image or PDF)', null=True, upload_to='feedback_forms/documents/')),
                ('deadline', models.DateField(blank=True, db_index=True, help_text='Last date for submission', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('allow_online_submission', models.BooleanField(default=True, help_text='Allow students to submit responses online')),
                ('allow_offline_download', models.BooleanField(default=True, help_text='Allow students to print blank form for physical submission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Department (Leave blank for all departments)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feedback_forms', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, help_text='Section (Leave blank for all sections)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.section')),
                ('year', models.ForeignKey(blank=True, help_text='Academic Year (Leave blank for all years)', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.year')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(help_text="e.g. Teacher's explanation and clarity of concepts", max_length=500)),
                ('question_type', models.CharField(choices=[('rating_5', '1 to 5 Star / Rating Scale (1-Poor, 5-Excellent)'), ('rating_10', '1 to 10 Numerical Scale'), ('text', 'Descriptive Text / Comments'), ('choice', 'Single Choice Selection')], default='rating_5', max_length=20)),
                ('options', models.TextField(blank=True, help_text='Comma-separated options for choice question', null=True)),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.feedbackform')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_mode', models.CharField(choices=[('online', 'Online Portal Submission'), ('offline_printed', 'Offline Printed Copy Fill-in')], default='online', max_length=20)),
                ('reference_no', models.CharField(db_index=True, max_length=35, unique=True)),
                ('overall_comments', models.TextField(blank=True, help_text='General comments or suggestions by student', null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.feedbackform')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_submissions', to='accounts.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(blank=True, null=True)),
                ('text_value', models.TextField(blank=True, null=True)),
                ('choice_value', models.CharField(blank=True, max_length=255, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.feedbackquestion')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.feedbacksubmission')),
            ],
            options={
                'ordering': ['question__order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbackform',
            index=models.Index(fields=['branch', 'year', 'semester', 'is_active'], name='core_feedba_branch__870368_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackform',
            index=models.Index(fields=['deadline', 'is_active'], name='core_feedba_deadlin_e3d6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['form', 'student'], name='core_feedba_form_id_4dcd7a_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacksubmission',
            index=models.Index(fields=['reference_no'], name='core_feedba_referen_8c3aab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedbacksubmission',
            unique_together={('form', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='feedbackanswer',
            unique_together={('submission', 'question')},
        ),
    ]
