# Generated by Django 6.1 on 2026-09-21 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_feedbackform_feedbackquestion_feedbacksubmission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether 1-day advance reminder email and notification have been dispatched'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
