# Generated by Django 4.2.7 on 2026-05-27 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_accounts_us_role_idx_accounts_us_role_1fa9a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
