# Generated by Django 4.2.7 on 2026-05-30 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_mobile',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Enter a valid phone number.')]),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
