# Generated by Django 4.2.7 on 2026-08-08 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_student_caste_student_fees_pending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('casual', 'Casual Leave (CL)'), ('sick', 'Sick Leave (SL)'), ('duty', 'On Duty (OD)'), ('earned', 'Earned Leave (EL)'), ('maternity', 'Maternity / Paternity Leave'), ('other', 'Other Leave')], db_index=True, default='casual', max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(db_index=True)),
                ('reason', models.TextField()),
                ('substitute_notes', models.TextField(blank=True, help_text='Class substitution or arrangement notes', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('action_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, help_text='Remarks by HOD or Admin', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_leaves', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.faculty')),
            ],
            options={
                'verbose_name': 'Faculty Leave Request',
                'verbose_name_plural': 'Faculty Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
