# Generated by Django 6.1 on 2026-08-12 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_facultyleaverequest'),
        ('core', '0011_remove_branch_course_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('curricular', 'Academic / Curricular'), ('cocurricular', 'Co-curricular'), ('extracurricular', 'Extra-curricular & Sports'), ('college', 'College & Institutional Achievement')], db_index=True, default='curricular', max_length=20),
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='College / Tuition Fee')),
                ('hostel_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hostel Fee (Optional)')),
                ('bus_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Bus / Transport Fee (Optional)')),
                ('nba_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='NBA Accreditation Fee')),
                ('exam_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Exam Fee')),
                ('book_bank_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Book Bank / Library Fee')),
                ('other_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Other / Misc Fee')),
                ('total_fee_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-calculated total sum of all fee components', max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid by student so far', max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Remaining balance due', max_digits=10)),
                ('status', models.CharField(choices=[('paid', 'Fully Paid'), ('partial', 'Partially Paid'), ('pending', 'Pending / Unpaid'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Admin/HOD/DEO notes, scholarship details or payment reference', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.year')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='accounts.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-academic_year__year', 'student__roll_number'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
    ]
