# Generated by Django 6.1 on 2026-08-14 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_achievement_category_studentfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfee',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount paid by student so far', max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='book_bank_fee',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=12, verbose_name='Book Bank / Library Fee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='bus_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Bus / Transport Fee (Optional)'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='college_fee',
            field=models.DecimalField(decimal_places=2, default=70000.0, max_digits=12, verbose_name='College / Tuition Fee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=78000.0, help_text='Remaining balance due', max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=12, verbose_name='Exam Fee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='hostel_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Hostel Fee (Optional)'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='nba_fee',
            field=models.DecimalField(decimal_places=2, default=3000.0, max_digits=12, verbose_name='NBA Accreditation Fee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=12, verbose_name='Other / Misc Fee'),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='total_fee_amount',
            field=models.DecimalField(decimal_places=2, default=78000.0, help_text='Auto-calculated total sum of all fee components', max_digits=12),
        ),
    ]
