# Generated by Django 4.2.7 on 2026-08-17 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_studentfee_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyleaverequest',
            name='session',
            field=models.CharField(choices=[('full', 'Full Day'), ('an', 'Afternoon Half Day (AN)'), ('fn', 'Morning Half Day (FN)')], db_index=True, default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='facultyleaverequest',
            name='leave_type',
            field=models.CharField(choices=[('casual', 'Casual Leave (CL)'), ('sick', 'Sick Leave (SL)'), ('half_day_an', 'Afternoon Half Day (AN) — 0.5 Day'), ('half_day_fn', 'Morning Half Day (FN) — 0.5 Day'), ('duty', 'On Duty (OD)'), ('earned', 'Earned Leave (EL)'), ('maternity', 'Maternity / Paternity Leave'), ('other', 'Other Leave')], db_index=True, default='casual', max_length=20),
        ),
    ]
