# Generated by Django 4.2.7 on 2026-08-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_facultyleaverequest_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='monthly_leave_limit',
            field=models.DecimalField(decimal_places=1, default=2.0, max_digits=4, verbose_name='Monthly Leave Limit (Days)'),
        ),
        migrations.AddField(
            model_name='facultyleaverequest',
            name='is_limit_exceeded',
            field=models.BooleanField(default=False, help_text="True if this leave request exceeds faculty's monthly limit (Emergency Leave)"),
        ),
    ]
