# Generated by Django 4.2.7 on 2026-08-31 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_questionpaper_options_and_more'),
        ('accounts', '0013_faculty_monthly_leave_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('DETAINED_ATTENDANCE', 'Detained - Attendance Shortage (<65%)'), ('DETAINED_CREDITS', 'Detained - Insufficient Credits'), ('READMITTED', 'Readmitted with Junior Batch')], db_index=True, default='REGULAR', max_length=25),
        ),
        migrations.AddField(
            model_name='student',
            name='detention_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_detained',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='original_batch_year',
            field=models.IntegerField(default=2024, help_text='Original joining batch year'),
        ),
        migrations.AddField(
            model_name='student',
            name='readmitted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentReadmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detention_type', models.CharField(choices=[('attendance', 'Attendance Shortage (<65% Detention)'), ('credits', 'Credit Shortage (Failed minimum credit criteria)')], default='attendance', max_length=20)),
                ('reason', models.TextField(help_text="Student's application reason to repeat the year with juniors")),
                ('hod_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('hod_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('hod_remarks', models.TextField(blank=True, null=True)),
                ('admin_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('admin_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False, help_text='True if student has been successfully moved to junior section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_readmission_approvals', to=settings.AUTH_USER_MODEL)),
                ('hod_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_readmission_approvals', to='accounts.faculty')),
                ('previous_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_readmissions', to='core.section')),
                ('previous_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_readmissions', to='core.year')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readmission_requests', to='accounts.student')),
                ('target_junior_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='junior_readmissions', to='core.section')),
                ('target_junior_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='junior_readmissions', to='core.year')),
            ],
            options={
                'verbose_name': 'Student Readmission Request',
                'verbose_name_plural': 'Student Readmission Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('medical', 'Medical Leave (Hospital / Doctor Certificate)'), ('od', 'On Duty (OD) — Academic / Hackathon / Conference'), ('sports', 'Sports / Cultural University Representation'), ('personal', 'Personal / Emergency Leave')], default='medical', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(help_text='Detailed reason for absence')),
                ('document', models.FileField(blank=True, help_text='Medical certificate or OD permission letter (PDF/Image)', null=True, upload_to='student_leave_docs/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Exemption Granted'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=15)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_student_leaves', to='accounts.faculty')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Student Leave Request',
                'verbose_name_plural': 'Student Leave Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
