# Generated by Django 6.1 on 2026-09-30 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_student_academic_status_student_detention_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhaar Number', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_year',
            field=models.CharField(blank=True, help_text='e.g. 2024-2027 or 2024-2028', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='admission_type',
            field=models.CharField(blank=True, default='CONVENOR', help_text='CONVENOR / MANAGEMENT', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='apaar_id',
            field=models.CharField(blank=True, help_text='Automated Permanent Academic Account Registry / APAAR ID', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='caste_category',
            field=models.CharField(blank=True, help_text='Caste Category (OC, BC-A, BC-B, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='caste_sub_category',
            field=models.CharField(blank=True, help_text='Sub-caste name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, default='B.TECH', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_admission',
            field=models.DateField(blank=True, help_text='Date of admission', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Date of birth', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='father_name',
            field=models.CharField(blank=True, help_text="Father's Name", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='inter_hall_ticket',
            field=models.CharField(blank=True, help_text='Inter or Diploma Hall Ticket', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(blank=True, help_text="Mother's Name", max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(blank=True, default='INDIAN', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='reservation_category',
            field=models.CharField(blank=True, help_text='OBC, EWS, NA', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_hall_ticket',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='ssc_pass_type',
            field=models.CharField(blank=True, default='REGULAR', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, default='ANDHRA PRADESH', max_length=100, null=True),
        ),
    ]
