# Generated by Django 6.1 on 2026-09-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_student_aadhaar_number_student_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(blank=True, help_text='Personal Email Address (e.g. Gmail)', max_length=254, null=True),
        ),
    ]
